### ISSUE TITLE
Precompiled binaries

### ISSUE THREAD

**Issue by marler8997** [marc-sturm/geGUI#2]
Any way you could add precompiled binaries? QT is a pretty big installation and would be a big hurdle for any users that just want to use the tool (aren't trying to develop anything with the tool).

**Comment by marc-sturm** [comment]
Hi Jonathan,

yes, thought about a more open license, but now it's GPL and I suppose I
cannot change it to something else...

I created a release with Windows binaries:
https://github.com/marc-sturm/geGUI/releases

If you find any bugs, or have any feature requests, please let me know.

Best,
  Marc

**Comment by Banbury** [comment]
Just for the record, you can change the license to whatever you want. It's your code after all. Especially since MIT is more permissive than GPL.
